services:
  backend:
    container_name: shroomhub-backend
    build:
      dockerfile: Dockerfile
      context: ./hub/backend
    ports:
      - "4040:4040"
    networks:
      - backend
    volumes:
      - ./hub/backend:/opt/app/api

networks:
  backend:
    external: true
