services:
  backend:
    container_name: shroomhub-backend
    build:
      dockerfile: Dockerfile
      context: ./hub/backend
    ports:
      - "4040:4040"
    volumes:
      - ./hub/backend:/opt/app/api
